# Configuration
baseURL = "https://reference.aspose.org/"
title = "Aspose Plugin References"
theme = "kb"

enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[languages]
  [languages.en]
    contentDir = "content/reference.aspose.org/home/en"
    languageName = "English"
    languageCode = "en"
    weight = 1
  [languages.de]
    contentDir = "content/reference.aspose.org/home/de"
    languageName = "Deutsch"
    languageCode = "de"
    weight = 2
  [languages.es]
    contentDir = "content/reference.aspose.org/home/es"
    languageName = "Español"
    languageCode = "es"
    weight = 3
  [languages.fr]
    contentDir = "content/reference.aspose.org/home/fr"
    languageName = "Français"
    languageCode = "fr"
    weight = 4
  [languages.ja]
    contentDir = "content/reference.aspose.org/home/ja"
    languageName = "日本語"
    languageCode = "ja"
    weight = 5
  [languages.ko]
    contentDir = "content/reference.aspose.org/home/ko"
    languageName = "한국어"
    languageCode = "ko"
    weight = 6
  [languages.ru]
    contentDir = "content/reference.aspose.org/home/ru"
    languageName = "Русский"
    languageCode = "ru"
    weight = 7
  [languages.zh]
    contentDir = "content/reference.aspose.org/home/zh"
    languageName = "中文"
    languageCode = "zh"
    weight = 8
  [languages.ar]
    contentDir = "content/reference.aspose.org/home/ar"
    languageName = "عربي"
    languageCode = "ar"
    weight = 9
  [languages.it]
    contentDir = "content/reference.aspose.org/home/it"
    languageName = "Italiano"
    languageCode = "it"
    weight = 10
  [languages.pt]
    contentDir = "content/reference.aspose.org/home/pt"
    languageName = "Português"
    languageCode = "pt"
    weight = 11
  [languages.pl]
    contentDir = "content/reference.aspose.org/home/pl"
    languageName = "Polski"
    languageCode = "pl"
    weight = 12
  [languages.fa]
    contentDir = "content/reference.aspose.org/home/fa"
    languageName = "فارسی"
    languageCode = "fa"
    weight = 13
  [languages.id]
    contentDir = "content/reference.aspose.org/home/id"
    languageName = "Indonesia"
    languageCode = "id"
    weight = 14
  [languages.cs]
    contentDir = "content/reference.aspose.org/home/cs"
    languageName = "čeština"
    languageCode = "cs"
    weight = 15
  [languages.vi]
    contentDir = "content/reference.aspose.org/home/vi"
    languageName = "Tiếng Việt"
    languageCode = "vi"
    weight = 16
  [languages.tr]
    contentDir = "content/reference.aspose.org/home/tr"
    languageName = "Türkçe"
    languageCode = "tr"
    weight = 17
  [languages.th]
    contentDir = "content/reference.aspose.org/home/th"
    languageName = "แบบไทย"
    languageCode = "th"
    weight = 18
  [languages.sv]
    contentDir = "content/reference.aspose.org/home/sv"
    languageName = "Svenska"
    languageCode = "sv"
    weight = 19
  [languages.el]
    contentDir = "content/reference.aspose.org/home/el"
    languageName = "Ελληνικά"
    languageCode = "el"
    weight = 20
  [languages.uk]
    contentDir = "content/reference.aspose.org/home/uk"
    languageName = "українська"
    languageCode = "uk"
    weight = 21

[deployment]
  [[deployment.targets]]
    name = "staging"
    URL = "s3://reference-qa.aspose.org/?region=us-west-2"
    cloudFrontDistributionID = "E2NZKCX96NYJB7"

  [[deployment.targets]]
    name = "production"
    URL = "s3://reference.aspose.org/?region=us-west-2"
    cloudFrontDistributionID = "E1ELI9S231ZZ2Z"

  [[deployment.matchers]]
    pattern = "^.+\\.(js|css|svg)$"
    cacheControl = "max-age=22880000, no-transform, public"
    gzip = true

  [[deployment.matchers]]
    pattern = "^.+\\.(png|jpg|ico)$"
    cacheControl = "max-age=22880000, no-transform, public"
    gzip = false

  [[deployment.matchers]]
    pattern = "^.+\\.(html|json)$"
    gzip = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = false

enableInlineShortcodes = true


[params]
# primary_color = "#02007e" #This was primary of the theme
#primary_color = "#3C8EC6"
#primary_color = "#3C8EC6"
primary_color = "#3C8DC5"
body_color = "#f9f9f9"
#text_color = "#636363" #theme color
text_color = "#333333"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"
