# Configuration
baseURL = "https://reference.aspose.org/tex"
title = "Aspose.TeX Plugin Reference"
theme = "docs"

enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[languages]
  [languages.en]
    contentDir = "content/reference.aspose.org/tex/en"
    languageName = "English"
    languageCode = "en"
    weight = 1
  [languages.de]
    contentDir = "content/reference.aspose.org/tex/de"
    languageName = "Deutsch"
    languageCode = "de"
    weight = 2
  [languages.es]
    contentDir = "content/reference.aspose.org/tex/es"
    languageName = "Español"
    languageCode = "es"
    weight = 3
  [languages.fr]
    contentDir = "content/reference.aspose.org/tex/fr"
    languageName = "Français"
    languageCode = "fr"
    weight = 4
  [languages.ja]
    contentDir = "content/reference.aspose.org/tex/ja"
    languageName = "日本語"
    languageCode = "ja"
    weight = 5
  [languages.ko]
    contentDir = "content/reference.aspose.org/tex/ko"
    languageName = "한국어"
    languageCode = "ko"
    weight = 6
  [languages.ru]
    contentDir = "content/reference.aspose.org/tex/ru"
    languageName = "Русский"
    languageCode = "ru"
    weight = 7
  [languages.zh]
    contentDir = "content/reference.aspose.org/tex/zh"
    languageName = "中文"
    languageCode = "zh"
    weight = 8
  [languages.ar]
    contentDir = "content/reference.aspose.org/tex/ar"
    languageName = "عربي"
    languageCode = "ar"
    weight = 9
  [languages.it]
    contentDir = "content/reference.aspose.org/tex/it"
    languageName = "Italiano"
    languageCode = "it"
    weight = 10
  [languages.pt]
    contentDir = "content/reference.aspose.org/tex/pt"
    languageName = "Português"
    languageCode = "pt"
    weight = 11
  [languages.pl]
    contentDir = "content/reference.aspose.org/tex/pl"
    languageName = "Polski"
    languageCode = "pl"
    weight = 12
  [languages.fa]
    contentDir = "content/reference.aspose.org/tex/fa"
    languageName = "فارسی"
    languageCode = "fa"
    weight = 13
  [languages.id]
    contentDir = "content/reference.aspose.org/tex/id"
    languageName = "Indonesia"
    languageCode = "id"
    weight = 14
  [languages.cs]
    contentDir = "content/reference.aspose.org/tex/cs"
    languageName = "čeština"
    languageCode = "cs"
    weight = 15
  [languages.vi]
    contentDir = "content/reference.aspose.org/tex/vi"
    languageName = "Tiếng Việt"
    languageCode = "vi"
    weight = 16
  [languages.tr]
    contentDir = "content/reference.aspose.org/tex/tr"
    languageName = "Türkçe"
    languageCode = "tr"
    weight = 17
  [languages.th]
    contentDir = "content/reference.aspose.org/tex/th"
    languageName = "แบบไทย"
    languageCode = "th"
    weight = 18
  [languages.sv]
    contentDir = "content/reference.aspose.org/tex/sv"
    languageName = "Svenska"
    languageCode = "sv"
    weight = 19
  [languages.el]
    contentDir = "content/reference.aspose.org/tex/el"
    languageName = "Ελληνικά"
    languageCode = "el"
    weight = 20
  [languages.uk]
    contentDir = "content/reference.aspose.org/tex/uk"
    languageName = "українська"
    languageCode = "uk"
    weight = 21

[deployment]
  [[deployment.targets]]
    name = "staging"
    URL = "s3://reference-qa.aspose.org/?prefix=tex/&region=us-west-2"
    cloudFrontDistributionID = "E2NZKCX96NYJB7"

  [[deployment.targets]]
    name = "production"
    URL = "s3://reference.aspose.org/?prefix=tex/&region=us-west-2"
    cloudFrontDistributionID = "E1ELI9S231ZZ2Z"

  [[deployment.matchers]]
    pattern = "^.+\\.(js|css|svg)$"
    cacheControl = "max-age=22880000, no-transform, public"
    gzip = true

  [[deployment.matchers]]
    pattern = "^.+\\.(png|jpg|ico)$"
    cacheControl = "max-age=22880000, no-transform, public"
    gzip = false

  [[deployment.matchers]]
    pattern = "^.+\\.(html|json)$"
    gzip = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    noClasses = false

enableInlineShortcodes = true


[params]
  [params.navbar]
    displayTitle = false

  [params.page]
    width = "normal"

  [params.theme]
    default = "system"
    displayToggle = true

  [params.footer]
    enable = false
    displayCopyright = false
    displayPoweredBy = false
    width = "normal"

  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  [params.search]
    enable = true
    type = "flexsearch"
    [params.search.flexsearch]
      index = "content"
      tokenize = "forward"

  [params.editURL]
    enable = false

  [params.highlight.copy]
    enable = true
    display = "always"

  [params.comments]
    enable = false
    type = "giscus"
